### ISSUE TITLE
Form layout styling issue 

### ISSUE THREAD

**Issue by Disitha395ra** [musnymubarak/EduLink-Peer-Tutoring-App#13]
<img width="962" alt="Screenshot 2024-12-04 215218" src="https://github.com/user-attachments/assets/1be10c30-c0b3-4b2b-ac38-9a31ad726245">

in this image i marked nav bar is no need , its disturb user interaction , and there is page scrolling issue

**Comment by Sathmi1234** [comment]
Done.
