### ISSUE TITLE
Course banner image issues

### ISSUE THREAD

**Issue by Disitha395ra** [musnymubarak/EduLink-Peer-Tutoring-App#14]
its better to add images into public folder
<img width="959" alt="banner" src="https://github.com/user-attachments/assets/12588586-484f-43e0-be5b-c8a30220ff7b">

@chamudithaperera use canva and add some stylish banners according to subjects 
@Sathmi1234  plz guide chmuditha to do this

**Comment by chamudithaperera** [comment]
@Disitha395ra done it
